package main.analysis;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import java.util.HashMap;

import main.interpreter.Environment;
import main.ast.AtomNode;
import main.ast.ConditionNode;
import main.ast.RuleNode;

public class StaticAnalyzer {
    private List<RuleNode> rules;
    private Environment env;

    public StaticAnalyzer(List<RuleNode> rules, Environment env) {
        this.rules = rules; 
        this.env = env;
    }

    public List<String> analyze() {
        List<String> messages = new ArrayList<>();

        messages.addAll(detectConflicts());
        messages.addAll(detectRedundancies());
        messages.addAll(detectInactiveRules());

        return messages;
    }

    public List<String> detectConflicts() {
        List<String> messages = new ArrayList<>();
        Map<String, List<String>> actionToRules = new HashMap<>();

        for (RuleNode rule : rules) {
            String action = rule.getAction().getName();     // Alert
            if (!actionToRules.containsKey(action)) {       // Si el map no contiene la accion relacionada, la mete y crea un arraylist relacionada a esta
                actionToRules.put(action, new ArrayList<>());
            }
            actionToRules.get(action).add(rule.getName());    // Si ya esta la accion en el map, mete el nombre de la relga que tiene la accion y asi sucesivamente con todas la reglas que contengan esta acción
        }   

        for (String action : actionToRules.keySet()) {         // keySet retorna las llaves y no sus valores, es decir aqui solo decimos que por accion haga:
            List<String> ruleNames = actionToRules.get(action);   // Mete el nombre de las reglas de esa accion en una lista llamada rulenames
            if (ruleNames.size() > 1) {                           //  si tiene mas de un elemento, osea, si hay una o mas reglas en la lista 
                messages.add("Action " + action + " generated by " + String.join(", ", ruleNames));    // Añade un mensaje warning para esta acción 
            }
        }
    return messages;
    }

    public List<String> detectRedundancies() {
        List<String> messages = new ArrayList<>();

        for (int i = 0; i < rules.size(); i++){
            for (int j = i + 1; j < rules.size(); j++){
                if (rules.get(i).getCondition().equals(rules.get(j).getCondition()) &&
                rules.get(i).getAction().getName().equals(rules.get(j).getAction().getName())) {
                messages.add("Redundant rules: " + rules.get(i).getName() + ", " + rules.get(j).getName());
                }
            }
        }
    return messages;
    }

    public List<String> detectInactiveRules() {
    List<String> messages = new ArrayList<>();

    for (RuleNode rule : rules) {
        if (!evaluateCondition(rule.getCondition())) {
            messages.add("Potentially inactive rule: " + rule.getName());
        }
    }

    return messages;
    }

    private boolean evaluateCondition(ConditionNode condition) {
    if (condition.isAnd()) {
        return evaluateCondition(condition.getLeft()) &&
               evaluateCondition(condition.getRight());
    }

    return evaluateAtom(condition.getAtom());
    }

    private boolean evaluateAtom(AtomNode atom) {
    if (atom.isComparison()) {
        if (!env.hasVariable(atom.getVariable())) {
            return false;
        }

        double variable = env.getVariable(atom.getVariable());
        double value = Double.parseDouble(atom.getValue());
        String operator = atom.getOperator();

        switch (operator) {
            case ">":
                return variable > value;
            case "<":
                return variable < value;
            case "=":
                return variable == value;
            default:
                throw new RuntimeException("Operador no válido: " + operator);
        }
    }

    return env.isFact(atom.getFact());
}
}
